### ISSUE TITLE
Feature Request: Pull certificates from server 

### ISSUE THREAD

**Issue by kub3let** [LetsDNS/letsdns#4]
Currently `LetsDNS` requires to give the certificate as path e.g. be locally available.

If `cert_x_path` is not set it should automatically try to connect to the given host:port e.g. `hostname`.`domain`:`tcp_ports` retrieve the certificate and generate the TLSA record for it.

In general it should not be expected for the certificate to be available on the same host that generates the TLSA records.

**Comment by rseichter** [comment]
Proper TLSA record rollover requires updating DNS data _before_ the certificates are rolled out to public servers, so I don't see how the feature you are asking for would be possible? Besides, LetsDNS was designed to handle DNS records. Retrieval of key material is better left to ACME clients like `dehydrated`, which then call LetsDNS to take care of DNS.

**Comment by kub3let** [comment]
The same problem exists right now, since the old dns tlsa record is cached and thus replacing it with a new one will still result in problems, you would need to keep the last 2 tlsa records (always or for the time of ttl timeout) in order to have a proper rollover which LetsDNS does not do right now.

Adding the tlsa record before or after does not make a difference in that regard right now.

Not a must have but it gives you the option to run LetsDNS without an acme client which might be preferred in some scenarios.

**Comment by rseichter** [comment]
In the documentation, I describe how LetsDNS is meant to be used to ensure proper TLSA record rollover, including DNS caching considerations. Order and timing of operations were key elements of my design, and the availability of certificates is a deliberate precondition, which is trivial when LetsDNS is invoked by an ACME client, as intended. Retrieval and distribution of certificates is the domain of ACME clients, not LetsDNS.
